name: 'Unlabel event'
description: 'Unlabel certain labels from an issue.'
author: 'steffektif'
inputs:
  label_name:
    description: 'The name of the label which should be removed.'
    required: true
  repo_token:
    description: 'Auth token to call the GitHub REST API'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
